### ISSUE TITLE
pypi package

### ISSUE THREAD

**Issue by kislyuk** [kracekumar/gist#3]
Hello,

It seems there are several issues with this package - it does not take files for the gist as command line arguments, is not compatible with Python 3, and appears to be a no-op on Python 2.

Would you be willing to let others maintain a different package under the name `gist` on PyPI? If so, you could add me (`kislyuk` on PyPI) to owners of your package. I would write a new Python package that maintains the same API but works.

**Comment by kracekumar** [comment]
Glad to see your message @kislyuk. You're now one of the owners of the package in PyPI. Please go ahead with changes. 

Good luck with the work.
